# UCFDetector Generalist Configuration
hf_repo: 'dubm/ucf-s'  # Hugging Face repository for downloading model files
train_config: 'generalist-sigmoid.yaml'  # pre-trained configuration file in HuggingFace
weights: 'generalist-sigmoid.pth'  # UCF model checkpoint in HuggingFace
backbone_weights: 'xception-best.pth'  # backbone model checkpoint in HuggingFace
