# UCFDetector Face Expert Configuration
hf_repo: 'dubm/ucf-test'  # Hugging Face repository for downloading model files
train_config: 'bm-faces-clahe-config.yaml'  # pre-trained configuration file in HuggingFace
weights: 'bm-faces-clahe.pth'  # UCF model checkpoint in HuggingFace
backbone_weights: 'xception_best.pth'  # backbone model checkpoint in HuggingFace
