# UCFDetector Face Expert Configuration
hf_repo: 'bitmind/ucf'  # Hugging Face repository for downloading model files
train_config: 'bm-faces-ffhq-config.yaml'  # pre-trained configuration file in HuggingFace
weights: 'bm-faces-ffhq.pth'  # UCF model checkpoint in HuggingFace
backbone_weights: 'xception_best.pth'  # backbone model checkpoint in HuggingFace
